# Generated by Django 5.0.1 on 2024-01-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='itemname',
            new_name='categoryname',
        ),
    ]
