# Generated by Django 5.0.1 on 2024-01-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0002_rename_itemname_menuitems_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='categoryname',
            new_name='itemname',
        ),
    ]
