# Generated by Django 5.0.1 on 2024-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0004_menucategory_remove_menu_cuisine_remove_menu_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('time_log', models.TimeField(help_text='Enter the exact time')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Menuitems',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
